import Header from '../components/header/Header';
import './globals.scss';
import type { Metadata } from 'next';
import { Open_Sans, Orbitron } from 'next/font/google';

export const metadata: Metadata = {
  title: 'News Net',
  description: 'Generated by create next app',
};

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
});

const orbitron = Orbitron({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${openSans.className} ${orbitron.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
